_schema: _schema
paths:
  uploads: public/
  static: static
collections_config:
  config:
    path: config
    name: Config
    icon: coffee
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_about:
    path: content/about
    name: Content About
    icon: content_cut
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_blog:
    path: content/blog
    name: Content Blog
    icon: content_copy
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_career:
    path: content/career
    name: Content Career
    icon: content_paste
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_contact:
    path: content/contact
    name: Content Contact
    icon: content_copy
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_homepage:
    path: content/homepage
    name: Content Homepage
    icon: contact_page
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_pages:
    path: content/pages
    name: Content Pages
    icon: contact_page
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_partners:
    path: content/partners
    name: Content Partners
    icon: content_paste
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_sections:
    path: content/sections
    name: Content Sections
    icon: collections
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_service:
    path: content/service
    name: Content Service
    icon: content_paste
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
